/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryRushnews.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rushnews/v1
// Description:
//   Rush News API
// Classes:
//   GTLQueryRushnews (3 custom class methods, 5 custom properties)

#import "GTLQueryRushnews.h"

#import "GTLRushnewsCollection.h"
#import "GTLRushnewsRushNews.h"

@implementation GTLQueryRushnews

@dynamic entityKey, fields, limit, order, pageToken;

#pragma mark -
#pragma mark "rushnews" methods
// These create a GTLQueryRushnews object.

+ (id)queryForRushnewsDeleteWithEntityKey:(NSString *)entityKey {
  NSString *methodName = @"rushnews.rushnews.delete";
  GTLQueryRushnews *query = [self queryWithMethodName:methodName];
  query.entityKey = entityKey;
  query.expectedObjectClass = [GTLRushnewsRushNews class];
  return query;
}

+ (id)queryForRushnewsInsertWithObject:(GTLRushnewsRushNews *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"rushnews.rushnews.insert";
  GTLQueryRushnews *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLRushnewsRushNews class];
  return query;
}

+ (id)queryForRushnewsList {
  NSString *methodName = @"rushnews.rushnews.list";
  GTLQueryRushnews *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLRushnewsCollection class];
  return query;
}

@end
