/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryRushnews.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rushnews/v1
// Description:
//   Rush News API
// Classes:
//   GTLQueryRushnews (3 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLRushnewsRushNews;

@interface GTLQueryRushnews : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *entityKey;
@property (assign) long long limit;
@property (copy) NSString *order;
@property (copy) NSString *pageToken;

#pragma mark -
#pragma mark "rushnews" methods
// These create a GTLQueryRushnews object.

// Method: rushnews.rushnews.delete
// Delete the given news if present
//  Authorization scope(s):
//   kGTLAuthScopeRushnewsUserinfoEmail
// Fetches a GTLRushnewsRushNews.
+ (id)queryForRushnewsDeleteWithEntityKey:(NSString *)entityKey;

// Method: rushnews.rushnews.insert
// Insert news
//  Authorization scope(s):
//   kGTLAuthScopeRushnewsUserinfoEmail
// Fetches a GTLRushnewsRushNews.
+ (id)queryForRushnewsInsertWithObject:(GTLRushnewsRushNews *)object;

// Method: rushnews.rushnews.list
// Return all news
//  Optional:
//   limit: long long
//   order: NSString
//   pageToken: NSString
//  Authorization scope(s):
//   kGTLAuthScopeRushnewsUserinfoEmail
// Fetches a GTLRushnewsCollection.
+ (id)queryForRushnewsList;

@end
