/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLRushnewsConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rushnews/v1
// Description:
//   Rush News API

#import "GTLRushnewsConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeRushnewsUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
