/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLRushnews.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rushnews/v1
// Description:
//   Rush News API

#import "GTLRushnewsConstants.h"

#import "GTLRushnewsCollection.h"
#import "GTLRushnewsRushNews.h"

#import "GTLQueryRushnews.h"
#import "GTLServiceRushnews.h"
