/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLRushnewsRushNews.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rushnews/v1
// Description:
//   Rush News API
// Classes:
//   GTLRushnewsRushNews (0 custom class methods, 4 custom properties)

#import "GTLRushnewsRushNews.h"

// ----------------------------------------------------------------------------
//
//   GTLRushnewsRushNews
//

@implementation GTLRushnewsRushNews
@dynamic body, entityKey, lastTouchDateTime, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"last_touch_date_time"
                                forKey:@"lastTouchDateTime"];
  return map;
}

@end
