/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLRushnewsRushNews.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rushnews/v1
// Description:
//   Rush News API
// Classes:
//   GTLRushnewsRushNews (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLRushnewsRushNews
//

@interface GTLRushnewsRushNews : GTLObject
@property (copy) NSString *body;
@property (copy) NSString *entityKey;
@property (copy) NSString *lastTouchDateTime;
@property (copy) NSString *title;
@end
