/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLRushnewsCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   rushnews/v1
// Description:
//   Rush News API
// Classes:
//   GTLRushnewsCollection (0 custom class methods, 2 custom properties)

#import "GTLRushnewsCollection.h"

#import "GTLRushnewsRushNews.h"

// ----------------------------------------------------------------------------
//
//   GTLRushnewsCollection
//

@implementation GTLRushnewsCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLRushnewsRushNews class]
                                forKey:@"items"];
  return map;
}

@end
